services:
  backend:
    mem_limit: 3g

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        VITE_MAPBOX_TOKEN: ${VITE_MAPBOX_TOKEN}
        VITE_API_BASE: ""
        NGINX_CONF: nginx.prod.conf
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/cloudflare:/etc/nginx/ssl:ro
